server:
  port: 9002
  
spring:
  application:
    name: catalog-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/commerce_catalog_db
    username: root
    password: carlosmanuel
  sql:
    init:
      mode: always
      platform: mysql
