server:
  port: 8081
spring:
  application:
    name: customers-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/customers_db
    username: root
    password: carlosmanuel
  sql:
    init:
      mode: always
      platform: mysql
management:
  endpoints.web.exposure.include: "health,info,metrics"
