server.port: 8083
spring:
  application.name: orders-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/orders_db
    username: demo
    password: demo
  sql.init:
    mode: always
    platform: mysql
