server:
  port: 9003
  
spring:
  application:
    name: sales-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/commerce_sales_db
    username: root
    password: carlosmanuel
  sql:
    init:
      mode: always
      platform: mysql
