server:
  port: 9001
  
spring:
  application:
    name: clients-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/commerce_clients_db
    username: root
    password: carlosmanuel
  sql:
    init:
      mode: always
      platform: mysql
      
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: when_authorized
